### ISSUE TITLE
KeyError in update_associated_spaces due to unexpected DataFrame column names

### ISSUE THREAD

**Issue by narchitect** [fclairec/core_module#1]
While running the main.py script in the `bim_space_graph` repository, I encountered a KeyError in the `update_associated_spaces` function located in the `IfcPEM.py` file. The error occurs because the script attempts to access DataFrame columns named "1" and "2", but the actual DataFrame (`relationship_df`) contains columns named "1" and "29" instead.

```
Traceback (most recent call last):
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/code/bim_space_graph/main.py", line 58, in <module>
    main()
  File "/home/appuser/code/bim_space_graph/main.py", line 34, in main
    instances = extract_data_from_ifc(cfg.design)
  File "/home/appuser/code/bim_space_graph/utils/extract_data_from_ifc.py", line 27, in extract_data_from_ifc
    pem.update_associated_spaces(relationship_df)
  File "/home/appuser/code/bim_space_graph/core_module/pem/IfcPEM.py", line 18, in update_associated_spaces
    relationship_df["pairs"] = relationship_df.apply(lambda x: (int(x["1"]), int(x["2"])), axis=1)
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/frame.py", line 9423, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/apply.py", line 678, in apply
    return self.apply_standard()
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/apply.py", line 798, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/apply.py", line 814, in apply_series_generator
    results[i] = self.f(v)
  File "/home/appuser/code/bim_space_graph/core_module/pem/IfcPEM.py", line 18, in <lambda>
    relationship_df["pairs"] = relationship_df.apply(lambda x: (int(x["1"]), int(x["2"])), axis=1)
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/home/appuser/miniconda/envs/py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: '2'
```

**Comment by narchitect** [comment]
`find_relation_type` function in `spatial_queires_kernel.py` loaded the csv file when testing. it's solved after removing the csv files from root_dir.
